---

easy_admin:
  design:
    menu:

      - label: 'menu.product'
        icon: 'shopping-basket'
        children:
          - { entity: 'Product', icon: 'th-list', label: 'menu.product.list' }
          - { entity: 'Product', icon: 'plus-circle', label: 'menu.product.add', params: { action: 'new' } }

      - label: 'menu.product_image'
        icon: 'image'
        children:
          - { entity: 'ProductImage', icon: 'th-list', label: 'menu.product_image.list' }
          - { entity: 'ProductImage', icon: 'plus-circle', label: 'menu.product_image.add', params: { action: 'new' } }

      - label: 'menu.category'
        icon: 'tags'
        children:
          - { entity: 'Category', icon: 'tags', label: 'menu.category.list' }
          - { entity: 'Category', icon: 'plus-circle', label: 'menu.category.add', params: { action: 'new' } }

      - label: 'menu.meta'
        icon: 'sticky-note-o'
        children:
          - { entity: 'CarouselSlide', icon: 'image', label: 'menu.carousel.list' }
          - { entity: 'Configuration', icon: 'cog', label: 'menu.configuration' }
          - { entity: 'ContentBlock', icon: 'th-large', label: 'menu.blocks.list' }
          - { entity: 'Hours', icon: 'building-o', label: 'menu.hours.list' }

      - label: 'menu.store'
        icon: 'money'
        children:
          - { entity: 'Coupon', label: 'menu.coupon', icon: 'tag' }
          - { entity: 'Order', label: 'menu.purchase', icon: 'credit-card' }

      - label: 'menu.logs'
        icon: 'terminal'
        children:
          - { entity: 'Email', icon: 'envelope', label: 'menu.email.list' }

...
