---

easy_admin:
  design:
    menu:

      - label: 'menu.product'
        icon: 'shopping-basket'
        children:
          - { entity: 'Product', icon: 'th-list', label: 'menu.product.list' }
          - { entity: 'Product', icon: 'plus-circle', label: 'menu.product.add', params: { action: 'new' } }

      - label: 'menu.category'
        icon: 'tags'
        children:
          - { entity: 'Category', icon: 'tags', label: 'menu.category.list' }
          - { entity: 'Category', icon: 'plus-circle', label: 'menu.category.add', params: { action: 'new' } }

      - label: 'menu.customer'
        entity: 'User'
        icon: 'users'

      - label: 'menu.purchase'
        entity: 'Order'
        icon: 'credit-card'

      - label: 'menu.address'
        entity: 'Address'

      - label: 'menu.about'

...
