---

liip_imagine :
  resolvers :
    default :
      web_path :
        cache_prefix: '%public_cache_dir%'

  filter_sets :
    cache         : ~
    product_thumbs :
      quality : 88
      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [480, 480], mode : outbound, allow_upscale : true }
        background  : { size : [484, 484], position : center, color : '#fff' }
      post_processors :
        jpegoptim   : { strip_all : true, max : 88, progressive : true }

    cart_product_thumb :
      quality : 88
      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [84, 84], mode : outbound, allow_upscale : true }
      post_processors :
        jpegoptim   : { strip_all : true, max : 88, progressive : true }

    product_view_thumbs :
      quality : 88
      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [800, 800], mode : outbound, allow_upscale : true }
        background  : { size : [840, 840], position : center, color : '#fff' }
      post_processors :
        jpegoptim   : { strip_all : true, max : 88, progressive : true }

    feed_photo_thumbs :
      quality : 88
      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min: [520, 380] }
        thumbnail   : { size : [520, 380], mode : outbound, allow_upscale : true }
        background  : { size : [560, 420], position : center, color : '#f2f1f3' }
      post_processors :
        jpegoptim   : { strip_all : true, max : 88, progressive : true }

    feed_social_thumbs :
      quality : 88
      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min: [700, 380] }
        thumbnail   : { size : [700, 380], mode : outbound, allow_upscale : true }
        background  : { size : [704, 384], position : center, color : '#f2f1f3' }
      post_processors :
        jpegoptim   : { strip_all : true, max : 88, progressive : true }

    carousel :
      quality : 90
      filters :
        auto_rotate : ~
        strip       : ~
        downscale   : { max: [2800, 1200] }
      post_processors :
        jpegoptim   : { strip_all : true, max : 90, progressive : true }
...
