---

liip_imagine :

  driver : "gmagick"

  resolvers :

    default :
      web_path : { cache_prefix : "assets/cache" }

  filter_sets :

    product_focus :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1014, 1014] }
        thumbnail   : { size : [1014, 1014], mode : outbound, allow_upscale : true }
        background  : { size : [1024, 1024], position : center, color : '#fff' }

    product_thumbs :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [480, 480], mode : outbound, allow_upscale : true }
        background  : { size : [484, 484], position : center, color : '#fff' }

    product_category_thumbs :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [320, 320], mode : outbound, allow_upscale : true }
        background  : { size : [322, 322], position : center, color : '#fff' }

    cart_product_thumb :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [84, 84], mode : outbound, allow_upscale : true }

    product_view_thumbs :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [800, 800], mode : outbound, allow_upscale : true }
        background  : { size : [840, 840], position : center, color : '#fff' }

    feed_photo_thumbs :

      jpeg_quality          : 85
      png_compression_level : 8
      data_loader           : remote
      cache                 : remote

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1004, 748] }
        thumbnail   : { size : [1004, 748], mode : outbound, allow_upscale : true }
        background  : { size : [1024, 768], position : center, color : '#f2f1f3' }

    feed_photo_lightbox_focus :

      jpeg_quality          : 90
      png_compression_level : 8
      data_loader           : remote
      cache                 : remote

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1980, 1280] }
        thumbnail   : { size : [1980, 1280], mode : outbound, allow_upscale : true }
        background  : { size : [2000, 1300], position : center, color : '#000' }

    #
    # lightbox - thumbnail images
    #
    feed_attachment_thumb :

      jpeg_quality          : 90
      png_compression_level : 8
      data_loader           : remote
      cache                 : remote

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1280, 940] }
        thumbnail   : { size : [1280, 940], mode : outbound, allow_upscale : true }
        background  : { size : [1300, 960], position : center, color : '#f2f1f3' }

    #
    # lightbox - enlarged images
    #
    feed_attachment_lightbox_focus :

      jpeg_quality          : 90
      png_compression_level : 8
      data_loader           : remote
      cache                 : remote

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1980, 1280] }
        thumbnail   : { size : [1980, 1280], mode : outbound, allow_upscale : true }
        background  : { size : [2000, 1300], position : center, color : '#000' }

    feed_social_thumbs :

      jpeg_quality          : 90
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1900, 1260] }
        thumbnail   : { size : [1900, 1260], mode : outbound, allow_upscale : true }
        background  : { size : [1920, 1280], position : center, color : '#f2f1f3' }

    #
    # lightbox - thumbnail images
    #
    lightbox_thumb :

      jpeg_quality          : 90
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1280, 940] }
        thumbnail   : { size : [1280, 940], mode : outbound, allow_upscale : true }
        background  : { size : [1290, 960], position : center, color : '#f2f1f3' }

    #
    # lightbox - enlarged images
    #
    lightbox_focus :

      jpeg_quality          : 90
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1980, 1280] }
        thumbnail   : { size : [1980, 1280], mode : outbound, allow_upscale : true }
        background  : { size : [2000, 1300], position : center, color : '#000' }

    #
    # home page carousel images
    #
    carousel :

      jpeg_quality          : 94
      png_compression_level : 9

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [2970, 1280] }
        downscale   : { max : [2970, 1280] }

...
