---

liip_imagine :

  driver : "gmagick"

  resolvers :

    default :
      web_path : { cache_prefix : "assets/cache" }

  filter_sets :

    product_lg :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1014, 1014], filter: LANCZOS }
        thumbnail   : { size : [1014, 1014], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [1024, 1024], position : center, color : '#fff' }

    product_thumb :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [480, 480], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [484, 484], position : center, color : '#fff' }

    category_thumb :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [320, 320], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [322, 322], position : center, color : '#fff' }

    product_thumb_sm :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [92, 92], mode : outbound, allow_upscale : true, filter: LANCZOS }

    product_thumb :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [800, 800], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [840, 840], position : center, color : '#fff' }

    product_thumb_no_border :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        thumbnail   : { size : [840, 840], mode : outbound, allow_upscale : true, filter: LANCZOS }

    feed_photo_thumb :

      jpeg_quality          : 85
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [620, 450], filter: LANCZOS }
        thumbnail   : { size : [620, 450], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [640, 470], position : center, color : '#f2f1f3' }

    feed_photo_lg :

      jpeg_quality          : 90
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1980, 1280], filter: LANCZOS }
        thumbnail   : { size : [1980, 1280], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [2000, 1300], position : center, color : '#000' }

    feed_media_thumb :

      jpeg_quality          : 90
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1260, 920], filter: LANCZOS }
        thumbnail   : { size : [1260, 920], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [1280, 940], position : center, color : '#f2f1f3' }

    feed_media_thumb_sm :

      jpeg_quality          : 90
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [620, 450], filter: LANCZOS }
        thumbnail   : { size : [620, 450], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [640, 470], position : center, color : '#f2f1f3' }

    feed_media_thumb_lg :

      jpeg_quality          : 90
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1260, 920], filter: LANCZOS }
        thumbnail   : { size : [1260, 920], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [1280, 940], position : center, color : '#f2f1f3' }

    feed_media_lg :

      jpeg_quality          : 90
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1980, 1280], filter: LANCZOS }

    feed_thumb :

      jpeg_quality          : 90
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1900, 1260], filter: LANCZOS }
        thumbnail   : { size : [1900, 1260], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [1920, 1280], position : center, color : '#f2f1f3' }

    lightbox_focus :

      jpeg_quality          : 90
      png_compression_level : 8

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [1980, 1280], filter: LANCZOS }
        thumbnail   : { size : [1980, 1280], mode : outbound, allow_upscale : true, filter: LANCZOS }
        background  : { size : [2000, 1300], position : center, color : '#000' }

    carousel :

      jpeg_quality          : 94
      png_compression_level : 9

      filters :
        auto_rotate : ~
        strip       : ~
        upscale     : { min : [2970, 1280], filter: LANCZOS }
        downscale   : { max : [2970, 1280], filter: LANCZOS }

...
