---

imports:
  - { resource: parameters.yml }
  - { resource: parameters_platform.php }
  - { resource: services.yml }
  - { resource: security.yml }
  - { resource: admin/ }

parameters:
  locale: en
  app.path.product_images: /uploads/images/products
  app.path.category_images: /uploads/images/categories

framework:
  translator: { fallbacks: ["%locale%"] }
  secret: "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation:
    enable_annotations: true
  templating:
    engines:
    - twig
  default_locale: "%locale%"
  trusted_hosts: ~
  trusted_proxies: ~
  session:
    handler_id:  ~
  fragments: ~
  http_method_override: true
  assets: ~

assetic:
  debug: '%kernel.debug%'
  use_controller: false
  bundles:
    - FOSUserBundle
    - AppBundle
  filters:
    cssrewrite: ~

twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"

doctrine:
  dbal:
    driver: mysqli
    host: "%database_host%"
    port: "%database_port%"
    dbname: "%database_name%"
    user: "%database_user%"
    password: "%database_password%"
    charset: UTF8
    server_version: 5.6
  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    metadata_cache_driver: apc
    query_cache_driver: apc
    result_cache_driver: apc
    filters:
      softdeleteable:
        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
        enabled: true

vich_uploader:
  db_driver: orm
  mappings:
    category_images:
      uri_prefix: %app.path.category_images%
      upload_destination: %kernel.root_dir%/../web/uploads/images/categories
    product_images:
      uri_prefix: %app.path.product_images%
      upload_destination: %kernel.root_dir%/../web/uploads/images/products

swiftmailer:
  transport: "%mailer_transport%"
  host: "%mailer_host%"
  username: "%mailer_user%"
  password:  "%mailer_password%"
  spool:
    type: memory

knp_menu:
  providers:
    builder_alias: false
    builder_service: false
    container_aware: false

stof_doctrine_extensions:
  default_locale: en_US
  uploadable:
    default_file_path:       %kernel.root_dir%/../web/uploads
    mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
    default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
  orm:
    default:
      timestampable: true
      blameable: false
      sluggable: true
      loggable: false
      sortable: true
      softdeleteable: true

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User

...
