---

#
# perforce file resource imports
#

imports :
  - { resource : config_dev.yml }


#
# main framework config
#

framework :
  test    : ~
  session :
    storage_id : session.storage.mock_file
  profiler :
    collect : false


#
# web profiler config
#

web_profiler :
  toolbar             : false
  intercept_redirects : false


#
# email transport
#


swiftmailer :
  disable_delivery : true


# EOF

...
