---

#
# perforce file resource imports
#

imports:
  - { resource: parameters.yml }
  - { resource: parameters_platform.php }
  - { resource: services.yml }
  - { resource: security.yml }
  - { resource: admin/ }
  - { resource: bundles/ }


#
# set parameters
#

parameters:

  locale : en

  srwc.url.domain_types:
    AjaxDataHref:
      domain:   'api.silverpapillon.com'
      template: 'data-href="%%s"'

  srwc.system_path.root : "%kernel.root_dir%/../web/"
  srwc.public_path.root : "/"

  srwc.system_path.upload : "%srwc.system_path.root%assets/uploads"
  srwc.public_path.upload : "%srwc.public_path.root%assets/uploads"
  srwc.system_path.cached : "%srwc.system_path.root%assets/cache"
  srwc.public_path.cached : "%srwc.public_path.root%assets/cache"

  srwc.public_path.image_products : "%srwc.public_path.upload%/products"
  srwc.system_path.image_products : "%srwc.system_path.upload%/products"
  srwc.public_path.image_carousel : "%srwc.public_path.upload%/carousel"
  srwc.system_path.image_carousel : "%srwc.system_path.upload%/carousel"

  srwc.asset_scr.file_name      : "app.js"
  srwc.asset_scr.file_name.prod : "app.min.js"
  srwc.asset_scr.package        : "javascripts"

  srwc.asset_css.file_name      : "app.css"
  srwc.asset_css.file_name.prod : "app.min.css"
  srwc.asset_css.package        : "stylesheets"

  srwc.google.static_maps_uri.api_endpoint : "https://maps.googleapis.com/maps/api/staticmap?center=${address}&markers=${address}&zoom=15&size=${size}&scale=2&maptype=roadmap&style=visibility:simplified&format=png32&key=${api_key}"
  srwc.google.street_view_uri.api_endpoint : "https://maps.googleapis.com/maps/api/streetview?location=${address}&size=${size}&fov=80&heading=180&pitch=2&key=${api_key}"
  srwc.google.simple_directions_href       : "https://www.google.com/maps/dir//${address}"


#
# main framework config
#

framework :
  translator : { fallbacks: ["%locale%"] }
  secret     : "%secret%"

  router :
    resource            : "%kernel.root_dir%/config/routing.yml"
    strict_requirements : ~

  form            : ~
  csrf_protection : ~
  validation      :
    enabled: true
    enable_annotations : true

  templating : { engines : [ "twig" ] }

  default_locale : "%locale%"

  trusted_hosts   : ~

  fragments            : ~
  session              : { handler_id : ~ }
  http_method_override : true

  assets :
    enabled        : true
    version        : 1.2.1
    version_format : "%%s?v=%%s"
    packages :
      images : { base_urls : [ "//silverpapillon.com/bundles/app/images" ] }



#
# asset management
#

assetic :
  debug          : '%kernel.debug%'
  use_controller : false

  bundles :
    - FOSUserBundle
    - AppBundle

  filters :
    cssrewrite : ~


#
# twig config
#

twig :
  debug            : "%kernel.debug%"
  strict_variables : "%kernel.debug%"


#
# doctrine (db) setup
#

doctrine :

  dbal :
    server_version : "%database_version%"

    driver   : "%database_driver%"
    host     : "%database_host%"
    port     : "%database_port%"
    dbname   : "%database_name%"
    user     : "%database_user%"
    password : "%database_password%"
    charset  : "%database_charset%"

  orm :
    auto_generate_proxy_classes : "%kernel.debug%"

    naming_strategy : doctrine.orm.naming_strategy.underscore
    auto_mapping    : true


#
# file uploader bundle config
#

vich_uploader :

  db_driver : orm
  mappings  :

    image_products :
      uri_prefix         : "%srwc.public_path.image_products%"
      upload_destination : "%srwc.system_path.image_products%"

    image_carousel :
      uri_prefix         : "%srwc.public_path.image_carousel%"
      upload_destination : "%srwc.system_path.image_carousel%"


#
# email transport
#

swiftmailer :
  transport : "%mailer_transport%"
  host      : "%mailer_host%"
  port      : "%mailer_port%"
  username  : "%mailer_user%"
  password  : "%mailer_password%"
  spool:
    type: db


#
# frields-of-symfony user bundle
#

fos_user :
  db_driver     : orm
  firewall_name : main
  user_class    : AppBundle\Entity\User

  from_email :
    address     : no-reply@silverpapillon.com
    sender_name : Silver Papillon


#
# pagination configuration
#

knp_paginator :
  default_options : { page_name  : "p" }
  template        : { pagination : "paginator.html.twig" }


#
# mail spooler
#

white_october_swift_mailer_db :
  entity_class       : AppBundle\Entity\Email
  keep_sent_messages : true


#
# disabled third-party bundles
#

#knp_menu:
#  providers:
#    builder_alias: false
#    builder_service: false
#    container_aware: false
#
#stof_doctrine_extensions:
#  default_locale: en_US
#  uploadable:
#    default_file_path:       %kernel.root_dir%/../web/uploads
#    mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
#    default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
#  orm:
#    default:
#      timestampable: true
#      blameable: false
#      sluggable: true
#      loggable: false
#      sortable: true
#      softdeleteable: true

# EOF

...
