---

#
# robots.txt route
#

robots_controller:
  resource : "@AppBundle/Controller/RobotsController.php"
  type     : annotation
  prefix   : /


#
# /admin routes
#

admin_controller:
  resource : "@AppBundle/Controller/AdminController.php"
  type     : annotation
  prefix   : /admin


#
# user routes
#

_fos_user:
  resource : "routing/fos-user.yml"


#
# image routes
#

liip_imagine_filter_runtime:
    path: /assets/images/resolve/{filter}/rc/{hash}/{path}
    defaults:
        _controller: '%liip_imagine.controller.filter_runtime_action%'
    methods:
        - GET
    requirements:
        filter: '[A-z0-9_-]*'
        path: .+

liip_imagine_filter:
    path: /assets/images/resolve/{filter}/{path}
    defaults:
        _controller: '%liip_imagine.controller.filter_action%'
    methods:
        - GET
    requirements:
        filter: '[A-z0-9_-]*'
        path: .+

#
# main app routes
#

_app:
  resource : "@AppBundle/Resources/config/routing/app.yml"


# EOF

...
