---

robots_controller:
  resource : "@AppBundle/Controller/RobotsController.php"
  type     : annotation
  prefix   : /

admin_controller:
  resource : "@AppBundle/Controller/AdminController.php"
  type     : annotation
  prefix   : /admin

_fos_user:
  resource : routing_fosuserbundle.yml

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_app:
  resource : "@AppBundle/Resources/config/routing/app.yml"

...
