---

easy_admin:
  entities:
    CarouselSlide:
      class: AppBundle\Entity\CarouselSlide
      label: 'Carousel'

      list:
        title: '%%entity_label%%'

        actions:

          - name  : 'edit'
            label : 'Edit'
            icon  : 'edit'

          - name  : 'delete'
            label : 'Delete'
            icon  : 'trash'

        fields:

          - enabled

          - property : 'weight'
            label    : 'Ordering'

          - caption

          - property  : 'image'
            type      : 'image'
            base_path : '%srwc.public_path.image_carousel%'

      show:
        fields:

          - enabled

          - property : 'weight'
            label    : 'Ordering'

          - caption

          - property  : 'image'
            type      : 'image'
            base_path : '%srwc.public_path.image_carousel%'

      form:
        fields:

          - label     : 'Media'
            type      : 'group'
            icon      : 'paperclip'
            css_class : 'col-sm-6'

          - property  : 'imageFile'
            label     : 'Image'
            type      : 'vich_image'

          - label     : 'Extended Information'
            type      : 'group'
            icon      : 'floppy-o'
            css_class : 'col-sm-6'

          - property  : 'enabled'
            label     : 'Published'

          - property  : 'weight'
            label     : 'Orderling'

          - label     : 'Description'
            type      : 'group'
            icon      : 'pencil'
            css_class : 'col-sm-12'

          - property  : 'caption'
            label     : 'Image Caption'
            type      : 'Ivory\CKEditorBundle\Form\Type\CKEditorType'

...
