---

easy_admin:
  entities:
    Category:
      class: AppBundle\Entity\Category
      label: 'Categories'

      list:
        title: '%%entity_label%%'

        actions:

          - name  : 'show'
            label : 'Show'
            icon  : 'search'

          - name  : 'edit'
            label : 'Edit'
            icon  : 'edit'

          - name  : 'delete'
            label : 'Delete'
            icon  : 'trash'

        fields:

          - id
          - name
          - enabled

          - property  : 'image'
            type      : 'image'
            base_path : '%app.path.category_images%'

      show:
        fields:

          - property  : 'name'
            label     : 'Label'
            css_class : 'large'

          - property  : 'image'
            type      : 'image'
            base_path : '%app.path.product_images%'

          - property  : 'image'
            type      : 'image'
            base_path : %app.path.category_images%

          - property  : 'enabled'
            label     : 'Published'

          - property  : 'products'

      form:
        fields:

          - label     : 'General Information'
            type      : 'group'
            icon      : 'pencil'
            css_class : 'col-sm-8'

          - name
          - products

          - property  : 'description'
            type      : 'Ivory\CKEditorBundle\Form\Type\CKEditorType'

          - type      : 'group'
            icon      : 'floppy-o'
            css_class : 'col-sm-4'
            label     : 'Publish State'

          - property  : 'enabled'
            label     : 'Published'

          - label     : 'Attachments'
            type      : 'group'
            icon      : 'paperclip'
            css_class : 'col-sm-4'

          - property  : 'imageFile'
            label     : 'Image'
            type      : 'vich_image'

...
