---

easy_admin:
  entities:
    Configuration:
      class: AppBundle\Entity\Configuration
      label: 'Configuration'
      disabled_actions: ['new', 'delete']

      list:
        title: '%%entity_label%%'

        actions:

          - name  : 'edit'
            label : 'Edit'
            icon  : 'edit'

        fields:

          - index
          - value

      show:
        fields:

          - index
          - value

      form:
        fields:

          - index
          - value

...
