---

easy_admin:
  entities:
    Hours:
      class: AppBundle\Entity\Hours
      label: 'Hours'

      list:
        title: '%%entity_label%%'

        actions:

          - name  : 'show'
            label : 'Show'
            icon  : 'search'

          - name  : 'edit'
            label : 'Edit'
            icon  : 'edit'

          - name  : 'delete'
            label : 'Delete'
            icon  : 'trash'

        fields:

          - property  : 'dow'
            label     : 'Day'

          - property : iso8601
            label    : 'ISO 8601'

          - closed

          - property  : timeOpen
            label     : 'Opening'

          - property  : timeClose
            label     : 'Closing'

      show:
        fields:

          - property  : 'dow'
            label     : 'Day'

          - property : iso8601
            label    : 'ISO 8601'

          - closed

          - property  : timeOpen
            label     : 'Opening Time'

          - property  : timeClose
            label     : 'Closing Time'

      form:
        fields:

          - label     : 'Day'
            type      : 'group'
            icon      : 'calendar-o'
            css_class : 'col-sm-6'

          - property  : 'dow'
            label     : 'Day'

          - property : iso8601
            label    : 'ISO-8601'

          - type      : 'divider'

          - closed

          - label     : 'Time'
            type      : 'group'
            icon      : 'clock-o'
            css_class : 'col-sm-6'

          - property  : timeOpen
            label     : 'Opening'

          - property  : timeClose
            label     : 'Closing'

...
