---

easy_admin:
  entities:
    Hours:
      class: AppBundle\Entity\Hours
      label: 'Hours'

      list:
        title: '%%entity_label%%'

        actions:

          - name  : 'show'
            label : 'Show'
            icon  : 'search'

          - name  : 'edit'
            label : 'Edit'
            icon  : 'edit'

          - name  : 'delete'
            label : 'Delete'
            icon  : 'trash'

        fields:

          - id
          - dow
          - weight
          - closed
          - timeOpen
          - timeClose

      form:
        fields:

          - label     : 'General Information'
            type      : 'group'
            icon      : 'pencil'
            css_class : 'col-sm-8 new-row'

          - property  : 'dow'
            label     : 'Day of the Week'
            css_class : 'col-sm-12'

          - property  : closed

          - property  : timeOpen
            label     : 'Opening Time'
            css_class : 'col-sm-12'

          - property  : timeClose
            label     : 'Closing Time'
            css_class : 'col-sm-12'

          - label     : 'Attributes'
            type      : 'group'
            icon      : 'tags'
            css_class : 'col-sm-4'

          - property  : weight
...
