---

easy_admin:
  entities:
    Order:
      class: AppBundle\Entity\OrderItem
      label: 'Order Items'
      disabled_actions: ['new', 'delete']

      list:
        title: '%%entity_label%%'

        actions:

          - name  : 'show'
            label : 'Show'
            icon  : 'md-eye'

          - name  : 'edit'
            label : 'Edit'
            icon  : 'edit'

...
