
#
# This file is part of the `src-run/<name>` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, please view the LICENSE.md
# file that was distributed with this source code.
#

app_root:
  path     : /
  defaults :
    _controller : AppBundle:Default:index
    route       : easyadmin
    permanent   : true

app_category_list:
  path     : /store/list
  defaults :
    _controller : AppBundle:Category:list

app_category_view:
  path     : /store/view/{category}
  defaults :
    _controller : AppBundle:Category:view

app_product_view:
  path     : /store/view/{category}/{productName}/{product}
  defaults :
    _controller : AppBundle:Product:view

app_cart_add:
  path     : /store/cart/add/{product}/{quantity}
  requirements:
    quantity: '\d+'
  defaults :
    _controller : AppBundle:Cart:add
    quantity: 1

app_cart_remove:
  path     : /store/cart/remove/select/{product}/{quantity}
  requirements:
    quantity: '\d+'
  defaults :
    _controller : AppBundle:Cart:remove
    quantity: 1

app_cart_remove_group:
  path     : /store/cart/remove/group/{product}
  requirements:
    quantity: '\d+'
  defaults :
    _controller : AppBundle:Cart:removeGroup

app_cart_clear:
  path     : /store/cart/clear
  defaults :
    _controller : AppBundle:Cart:clear

app_cart_view:
  path     : /store/cart
  defaults :
    _controller : AppBundle:Cart:view

app_cart_checkout:
  path     : /store/checkout
  defaults :
    _controller : AppBundle:Cart:checkout

app_location:
  path     : /location
  defaults :
    _controller : AppBundle:Location:index

app_orders_list:
  path     : /store/orders
  defaults :
    _controller : AppBundle:Orders:view

app_feed_view:
  path     : /feed
  defaults :
    _controller : AppBundle:Feed:index

app_account_view:
  path     : /account
  defaults :
    _controller : AppBundle:Account:view

app_contact_view:
  path     : /contact
  defaults :
    _controller : AppBundle:Contact:index

# EOF
