services :

  app.cart:
    class   : AppBundle\Model\Cart
    factory :
      - AppBundle\Model\Cart
      - create
    arguments :
      - "@session"
      - "@doctrine.orm.default_entity_manager"
      - "@app.manager.configuration"
      - "@app.location_lookup.resolver"

  app.slugger :
    class : AppBundle\Util\Slugger

  app.mapper.static :
    class : AppBundle\Util\Mapper
    calls :
      - [setCache,         [ "@cache.app" ]]
      - [setConfigManager, [ "@app.manager.configuration" ]]
      - [setUri,           [ "%srwc.google.static_maps_uri.api_endpoint%" ]]
      - [setApi,           [ "%google_api_key_static_maps%" ]]
      - [setOutputPath,    [ "%srwc.system_path.root%", "%srwc.system_path.cached%" ]]

  app.mapper.street :
    class : AppBundle\Util\Mapper
    calls :
      - [setCache,         [ "@cache.app" ]]
      - [setConfigManager, [ "@app.manager.configuration" ]]
      - [setUri,           [ "%srwc.google.street_view_uri.api_endpoint%" ]]
      - [setApi,           [ "%google_api_key_street_view%" ]]
      - [setOutputPath,    [ "%srwc.system_path.root%", "%srwc.system_path.cached%" ]]

  app.directions :
    class : AppBundle\Util\Directions
    calls :
      - [setConfigManager, [ "@app.manager.configuration" ]]
      - [setUri, ["%srwc.google.simple_directions_href%"]]

  app.twig_extension_helper.cart:
    class  : AppBundle\Twig\Helper\CartTwigExtensionHelper
    public : false
    arguments :
      - "@app.cart"

  app.twig_extension.cart:
    class  : AppBundle\Twig\CartTwigExtension
    public : false
    arguments :
      - "@app.twig_extension_helper.cart"
    tags   :
      - { name : twig.extension }

  app.twig_extension.category_manager:
    class  : AppBundle\Twig\CategoryManagerExtension
    public : false
    calls  :
      - [setCategoryManager, ["@app.manager.category"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.slugger:
    class  : AppBundle\Twig\SluggerExtension
    public : false
    arguments:
      - "@app.slugger"
    tags   :
      - { name : twig.extension }

  app.twig_extension.content_block:
    class  : AppBundle\Twig\ContentBlockExtension
    public : false
    calls  :
      - [setContentBlockManager, ["@app.manager.content_block"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.carousel_slide:
    class  : AppBundle\Twig\CarouselSlideExtension
    public : false
    arguments:
      - "@app.manager.carousel_slide"
    tags   :
      - { name : twig.extension }

  app.twig_extension.configuration:
    class  : AppBundle\Twig\ConfigurationExtension
    public : false
    calls  :
      - [setConfigurationManager, ["@app.manager.configuration"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension_helper.url_to_file:
    class  : AppBundle\Twig\Helper\UrlToFileExtensionHelper
    public : false
    arguments :
      - "%srwc.system_path.upload%"
      - "%srwc.public_path.upload%"

  app.twig_extension.url_to_file:
    class  : AppBundle\Twig\UrlToFileExtension
    public : false
    arguments:
      - "@app.twig_extension_helper.url_to_file"
    tags   :
      - { name : twig.extension }

  app.twig_extension_helper.url_transformer:
    class  : AppBundle\Twig\Helper\UrlTransformerExtensionHelper
    public : false

  app.twig_extension.url_transformer:
    class  : AppBundle\Twig\UrlTransformerExtension
    public : false
    arguments:
      - "@app.twig_extension_helper.url_transformer"
    tags   :
      - { name : twig.extension }

  app.twig_extension.modified:
    class     : AppBundle\Twig\ModifiedExtension
    public    : false
    arguments :
      - '@app.twig_locator'
    tags      :
      - { name : twig.extension }

  app.twig_extension_helper.framework_reflect:
    class     : AppBundle\Twig\Helper\FrameworkReflectExtensionHelper
    public    : false
    arguments :
      - '%kernel.environment%'
      - '%kernel.debug%'

  app.twig_extension.framework_reflect:
    class     : AppBundle\Twig\FrameworkReflectTwigExtension
    public    : false
    arguments :
      - '@app.twig_extension_helper.framework_reflect'
    tags :
      - { name : twig.extension }

  app.twig_locator:
    class     : AppBundle\Twig\Locator\TemplateLocator
    calls     :
      - [setKernelRoot, ["%kernel.root_dir%"]]
    arguments :
      - '@twig.loader'

  app.twig_extension.moment:
    class  : SR\WonkaBundle\Twig\MomentTwigExtension
    public : false
    tags   :
      - { name : twig.extension }

  app.twig_extension.fb:
    class  : AppBundle\Twig\FacebookExtension
    public : false
    calls  :
      - [setProvider, ["@app.fb.provider.page_feed"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension_helper.icon:
    class  : AppBundle\Twig\Helper\IconExtensionHelper
    public : false

  app.twig_extension.icon:
    class  : AppBundle\Twig\IconExtension
    public : false
    arguments:
      - "@app.twig_extension_helper.icon"
    tags   :
      - { name : twig.extension }

  app.twig_extension.session:
    class  : AppBundle\Twig\SessionExtension
    public : false
    tags   :
      - { name : twig.extension }

  app.twig_extension_helper.vich_file_path:
    class  : AppBundle\Twig\Helper\VichFilePathExtensionHelper
    public : false
    arguments :
      - product : '%srwc.public_path.image_products%'
        carousel : '%srwc.public_path.image_carousel%'

  app.twig_extension.vich_file_path:
    class  : AppBundle\Twig\VichFilePathExtension
    public : false
    arguments:
      - "@app.twig_extension_helper.vich_file_path"
    tags :
      - { name : twig.extension }

  app.twig_extension.strip_html:
    class  : AppBundle\Twig\StripHtmlExtension
    public : false
    tags :
      - { name : twig.extension }

  app.manager.category :
    class : AppBundle\Manager\CategoryManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.product :
    class : AppBundle\Manager\ProductManager
    calls :
      - [setPaginator, ["@knp_paginator"]]
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.hours :
    class : AppBundle\Manager\HoursManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.content_block :
    class : AppBundle\Manager\ContentBlockManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.carousel_slide :
    class : AppBundle\Manager\CarouselSlideManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.configuration :
    class : AppBundle\Manager\ConfigurationManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.fb.provider.page_feed :
    class     : AppBundle\Component\Facebook\Provider\FeedProvider
    arguments :
      - '@app.fb.auth'
    calls :
      - [setCache, ['@cache.app']]

  app.fb.auth :
    class     : AppBundle\Component\Facebook\Authentication\AuthenticationServerSide
    arguments :
      - '%facebook_page_id%'
      - '%facebook_app_id%'
      - '%facebook_app_secret%'
      - '%facebook_graph_version%'
    calls :
      - [setCache, ['@cache.app']]

  #
  # liip remote loader
  #
  app.liip_bundle.remote.loader:
    class     : AppBundle\Component\Imagine\Loader\RemoteLoader
    arguments :
      - "%kernel.cache_dir%/liip/"
      - "@liip_imagine.binary.mime_type_guesser"
      - "@liip_imagine.extension_guesser"
      - "@app.liip_bundle.remote.loader_cache"
    tags:
      - { name: liip_imagine.binary.loader, loader: remote }

  #
  # liip remote loader cache
  #
  app.liip_bundle.remote.loader_cache:
    class     : AppBundle\Component\Imagine\Loader\Cache\RemoteLoaderCache
    arguments :
      - "%kernel.cache_dir%/liip-loader-cache"
      - "remote"

  #
  # liip remote resolver
  #
  app.liip_bundle.remote.resolver:
    class     : AppBundle\Component\Imagine\Resolver\RemoteResolver
    arguments :
      - "@filesystem"
      - "@router.request_context"
      - "@app.liip_bundle.remote.loader"
      - "%kernel.root_dir%/../web"
      - "%public_cache_dir%"
    tags:
      - { name: liip_imagine.cache.resolver, resolver: remote }

  #
  # location lookup cache
  #
  app.location_lookup.cache:
    class     : AppBundle\Component\Cache\Cache
    arguments :
      - "@cache.app"
    calls     :
      - [setEnabled, [false]]

  #
  # maxmind location resolver
  #
  app.location_lookup.maxmind.resolver:
    class     : AppBundle\Component\Location\Resolver\MaxMindResolver
    arguments :
      - "%location_lookup.max_mind.database%"

  #
  # ip2location location resolver
  #
  app.location_lookup.ip2location.resolver:
    class     : AppBundle\Component\Location\Resolver\Ip2LocationResolver
    arguments :
      - "%location_lookup.ip2location.database%"

  #
  # location lookup master resolver
  #
  app.location_lookup.resolver:
    class     : AppBundle\Component\Location\LocationLookup
    arguments :
      - ["@app.location_lookup.maxmind.resolver", "@app.location_lookup.ip2location.resolver"]
      - "@app.location_lookup.cache"
      - 30
    calls :
      - [setRequestStack, ["@request_stack"]]
