services :

  app.cart:
    class   : AppBundle\Model\Cart
    factory :
      - AppBundle\Model\Cart
      - create
    arguments :
      - "@session"
      - "@doctrine.orm.default_entity_manager"

  app.slugger :
    class : AppBundle\Util\Slugger

  app.mapper.static :
    class : AppBundle\Util\Mapper
    calls :
      - [setBlockManager, ["@app.manager.content_block"]]
      - [setUri, ["%google_static_maps_uri%"]]
      - [setApi, ["%google_api_key_static_maps%"]]
      - [setCachePaths, ["%app.sys_path.cache%", "%app.web_path.cache%"]]

  app.mapper.street :
    class : AppBundle\Util\Mapper
    calls :
      - [setBlockManager, ["@app.manager.content_block"]]
      - [setUri, ["%google_street_view_uri%"]]
      - [setApi, ["%google_api_key_street_view%"]]
      - [setCachePaths, ["%app.sys_path.cache%", "%app.web_path.cache%"]]

  app.directions :
    class : AppBundle\Util\Directions
    calls :
      - [setBlockManager, ["@app.manager.content_block"]]
      - [setUri, ["%google_directions_uri%"]]

  app.twig_extension.cart:
    class  : AppBundle\Twig\CartExtension
    public : false
    calls  :
      - [setCart, ["@app.cart"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.category_manager:
    class  : AppBundle\Twig\CategoryManagerExtension
    public : false
    calls  :
      - [setCategoryManager, ["@app.manager.category"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.slugger:
    class  : AppBundle\Twig\SluggerExtension
    public : false
    calls  :
      - [setSlugger, ["@app.slugger"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.content_block:
    class  : AppBundle\Twig\ContentBlockExtension
    public : false
    calls  :
      - [setContentBlockManager, ["@app.manager.content_block"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.carousel_slide:
    class  : AppBundle\Twig\CarouselSlideExtension
    public : false
    calls  :
      - [setCarouselSlideManager, ["@app.manager.carousel_slide"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.url_to_file:
    class  : AppBundle\Twig\UrlToFileExtension
    public : false
    calls  :
      - [setSysDir, ["%app.sys_path.upload%"]]
      - [setWebDir, ["%app.web_path.upload%"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.moment:
    class  : SR\WonkaBundle\Twig\MomentTwigExtension
    public : false
    tags   :
      - { name : twig.extension }

  app.twig_extension.vich_file_path:
    class  : AppBundle\Twig\VichFilePathExtension
    public : false
    calls  :
      - [setPaths, [{product: '%app.path.product_images%', category: '%app.path.category_images%', carousel: '%app.path.carousel_images%'}]]
    tags   :
      - { name : twig.extension }

  app.manager.category :
    class : AppBundle\Manager\CategoryManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.product :
    class : AppBundle\Manager\ProductManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.hours :
    class : AppBundle\Manager\HoursManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.content_block :
    class : AppBundle\Manager\ContentBlockManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.carousel_slide :
    class : AppBundle\Manager\CarouselSlideManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.fb.provider.page_feed :
    class     : AppBundle\Component\Facebook\Provider\PageFeedProvider
    arguments :
      - '%facebook_page_id%'
      - '%facebook_app_id%'
      - '%facebook_app_secret%'
      - '%facebook_graph_version%'
    calls :
      - [setCache, ['@cache.app']]
