services :

  app.cart:
    class   : AppBundle\Model\Cart
    factory :
      - AppBundle\Model\Cart
      - create
    arguments :
      - "@session"
      - "@doctrine.orm.default_entity_manager"
      - "@app.manager.configuration"

  app.slugger :
    class : AppBundle\Util\Slugger

  app.mapper.static :
    class : AppBundle\Util\Mapper
    calls :
      - [setCache,         [ "@cache.app" ]]
      - [setConfigManager, [ "@app.manager.configuration" ]]
      - [setUri,           [ "%srwc.google.static_maps_uri.api_endpoint%" ]]
      - [setApi,           [ "%google_api_key_static_maps%" ]]
      - [setOutputPath,    [ "%srwc.system_path.root%", "%srwc.system_path.cached%" ]]

  app.mapper.street :
    class : AppBundle\Util\Mapper
    calls :
      - [setCache,         [ "@cache.app" ]]
      - [setConfigManager, [ "@app.manager.configuration" ]]
      - [setUri,           [ "%srwc.google.street_view_uri.api_endpoint%" ]]
      - [setApi,           [ "%google_api_key_street_view%" ]]
      - [setOutputPath,    [ "%srwc.system_path.root%", "%srwc.system_path.cached%" ]]

  app.directions :
    class : AppBundle\Util\Directions
    calls :
      - [setConfigManager, [ "@app.manager.configuration" ]]
      - [setUri, ["%srwc.google.simple_directions_href%"]]

  app.twig_extension.cart:
    class  : AppBundle\Twig\CartExtension
    public : false
    calls  :
      - [setCart, ["@app.cart"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.category_manager:
    class  : AppBundle\Twig\CategoryManagerExtension
    public : false
    calls  :
      - [setCategoryManager, ["@app.manager.category"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.slugger:
    class  : AppBundle\Twig\SluggerExtension
    public : false
    calls  :
      - [setSlugger, ["@app.slugger"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.content_block:
    class  : AppBundle\Twig\ContentBlockExtension
    public : false
    calls  :
      - [setContentBlockManager, ["@app.manager.content_block"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.carousel_slide:
    class  : AppBundle\Twig\CarouselSlideExtension
    public : false
    calls  :
      - [setCarouselSlideManager, ["@app.manager.carousel_slide"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.configuration:
    class  : AppBundle\Twig\ConfigurationExtension
    public : false
    calls  :
      - [setConfigurationManager, ["@app.manager.configuration"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.url_to_file:
    class  : AppBundle\Twig\UrlToFileExtension
    public : false
    calls  :
      - [setSysDir, ["%srwc.system_path.upload%"]]
      - [setWebDir, ["%srwc.public_path.upload%"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.url_transformer:
    class  : AppBundle\Twig\UrlTransformerExtension
    public : false
    tags   :
      - { name : twig.extension }

  app.twig_extension.modified:
    class     : AppBundle\Twig\ModifiedExtension
    public    : false
    arguments :
      - '@app.twig_locator'
    tags      :
      - { name : twig.extension }

  app.twig_extension.framework_reflect:
    class     : AppBundle\Twig\FrameworkReflectExtension
    public    : false
    arguments :
      - '%kernel.environment%'
      - '%kernel.debug%'
    tags :
      - { name : twig.extension }

  app.twig_locator:
    class     : AppBundle\Twig\Locator\TemplateLocator
    arguments :
      - '@twig.loader'

  app.twig_extension.moment:
    class  : SR\WonkaBundle\Twig\MomentTwigExtension
    public : false
    tags   :
      - { name : twig.extension }

  app.twig_extension.fb:
    class  : AppBundle\Twig\FacebookExtension
    public : false
    calls  :
      - [setProvider, ["@app.fb.provider.page_feed"]]
    tags   :
      - { name : twig.extension }

  app.twig_extension.icon:
    class  : AppBundle\Twig\IconExtension
    public : false
    tags   :
      - { name : twig.extension }

  app.twig_extension.session:
    class  : AppBundle\Twig\SessionExtension
    public : false
    tags   :
      - { name : twig.extension }

  app.twig_extension.vich_file_path:
    class  : AppBundle\Twig\VichFilePathExtension
    public : false
    calls  :
      - [setPaths, [{ product : '%srwc.public_path.image_products%', carousel : '%srwc.public_path.image_carousel%' }]]
    tags :
      - { name : twig.extension }

  app.manager.category :
    class : AppBundle\Manager\CategoryManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.product :
    class : AppBundle\Manager\ProductManager
    calls :
      - [setPaginator, ["@knp_paginator"]]
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.hours :
    class : AppBundle\Manager\HoursManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.content_block :
    class : AppBundle\Manager\ContentBlockManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.carousel_slide :
    class : AppBundle\Manager\CarouselSlideManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.manager.configuration :
    class : AppBundle\Manager\ConfigurationManager
    calls :
      - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]

  app.fb.provider.page_feed :
    class     : AppBundle\Component\Facebook\Provider\FeedProvider
    arguments :
      - '@app.fb.auth'
    calls :
      - [setCache, ['@cache.app']]

  app.fb.auth :
    class     : AppBundle\Component\Facebook\Authentication\AuthenticationServerSide
    arguments :
      - '%facebook_page_id%'
      - '%facebook_app_id%'
      - '%facebook_app_secret%'
      - '%facebook_graph_version%'
    calls :
      - [setCache, ['@cache.app']]

  #
  # liip remote loader
  #
  app.liip_bundle.remote.loader:
    class     : AppBundle\Component\Imagine\Loader\RemoteLoader
    arguments :
      - "%kernel.cache_dir%/liip/"
      - "@liip_imagine.binary.mime_type_guesser"
      - "@liip_imagine.extension_guesser"
      - "@app.liip_bundle.remote.loader_cache"
    tags:
      - { name: liip_imagine.binary.loader, loader: remote }

  #
  # liip remote loader cache
  #
  app.liip_bundle.remote.loader_cache:
    class     : AppBundle\Component\Imagine\Loader\Cache\RemoteLoaderCache
    arguments :
      - "%kernel.cache_dir%/liip-loader-cache"
      - "remote"

  #
  # liip remote resolver
  #
  app.liip_bundle.remote.resolver:
    class     : AppBundle\Component\Imagine\Resolver\RemoteResolver
    arguments :
      - "@filesystem"
      - "@router.request_context"
      - "@app.liip_bundle.remote.loader"
      - "%kernel.root_dir%/../web"
      - "%public_cache_dir%"
    tags:
      - { name: liip_imagine.cache.resolver, resolver: remote }
