"http://{default}/":
    type: upstream
    upstream: "php:http"
    cache:
        enabled: false
    ssi:
        enabled: false

"http://www.{default}/":
    type: redirect
    to: "http://{default}/"